
/*const categoryByTime =
[
    {
        date:"7.1",
        category:
        [
            {
                title:"吵",
                quantity:1
            },
            {
                title:"髒",
                quantity:2
            },
            {
                title:"污染",
                quantity:2
            },
            {
                title:"亂停車",
                quantity:1
            },
            {
                title:"吵",
                quantity:4
            },
            {
                title:"髒",
                quantity:2
            },
            {
                title:"污染",
                quantity:1
            },
            {
                title:"亂停車",
                quantity:7
            },
            {
                title:"亂停車",
                quantity:1
            },
        ]
    },
    {
        date:"7.2",
        category:
        [
            {
                title:"吵",
                quantity:2
            },
            {
                title:"髒",
                quantity:4
            },
            {
                title:"污染",
                quantity:7
            },
            {
                title:"亂停車",
                quantity:7
            },
            {
                title:"吵",
                quantity:4
            },
            {
                title:"髒",
                quantity:2
            },
            {
                title:"污染",
                quantity:7
            },
            {
                title:"亂停車",
                quantity:2
            },
            {
                title:"亂停車",
                quantity:7
            },
        ]
    },
    {
        date:"7.3",
        category:
        [
            {
                title:"吵",
                quantity:3
            },
            {
                title:"髒",
                quantity:2
            },
            {
                title:"污染",
                quantity:2
            },
            {
                title:"亂停車",
                quantity:7
            },
            {
                title:"吵",
                quantity:4
            },
            {
                title:"髒",
                quantity:2
            },
            {
                title:"污染",
                quantity:1
            },
            {
                title:"亂停車",
                quantity:7
            },
            {
                title:"亂停車",
                quantity:3
            },
        ]
    },
    {
        date:"7.4",
        category:
        [
            {
                title:"吵",
                quantity:4
            },
            {
                title:"髒",
                quantity:4
            },
            {
                title:"污染",
                quantity:1
            },
            {
                title:"亂停車",
                quantity:3
            },
            {
                title:"吵",
                quantity:4
            },
            {
                title:"髒",
                quantity:2
            },
            {
                title:"污染",
                quantity:9
            },
            {
                title:"亂停車",
                quantity:7
            },
            {
                title:"亂停車",
                quantity:7
            },
        ]
    },
    {
        date:"7.5",
        category:
        [
            {
                title:"吵",
                quantity:3
            },
            {
                title:"髒",
                quantity:2
            },
            {
                title:"污染",
                quantity:4
            },
            {
                title:"亂停車",
                quantity:4
            },
            {
                title:"吵",
                quantity:4
            },
            {
                title:"髒",
                quantity:2
            },
            {
                title:"污染",
                quantity:7
            },
            {
                title:"亂停車",
                quantity:0
            },
            {
                title:"亂停車",
                quantity:1
            },
        ]
    },
    {
        date:"7.6",
        category:
        [
            {
                title:"吵",
                quantity:6
            },
            {
                title:"髒",
                quantity:4
            },
            {
                title:"污染",
                quantity:6
            },
            {
                title:"亂停車",
                quantity:7
            },
            {
                title:"吵",
                quantity:4
            },
            {
                title:"髒",
                quantity:2
            },
            {
                title:"污染",
                quantity:1
            },
            {
                title:"亂停車",
                quantity:2
            },
            {
                title:"亂停車",
                quantity:4
            },
        ]
    },
    {
        date:"7.7",
        category:
        [
            {
                title:"吵",
                quantity:7
            },
            {
                title:"髒",
                quantity:2
            },
            {
                title:"污染",
                quantity:1
            },
            {
                title:"亂停車",
                quantity:7
            },
            {
                title:"吵",
                quantity:4
            },
            {
                title:"髒",
                quantity:5
            },
            {
                title:"污染",
                quantity:4
            },
            {
                title:"亂停車",
                quantity:3
            },
            {
                title:"亂停車",
                quantity:2
            },
        ]
    },

] 
*/
const categoryByTime = {
    Area:{
    '07/01/2018':{
        'a':3,
        'b':4,
        'c':3
    },
    '07/02/2018':{
        'a':2,
        'b':8,
        'c':3
    },
    '07/03/2018':{
        'a':10,
        'b':0,
        'c':1
    },
    '07/04/2018':{
        'a':23,
        'b':5,
        'c':2
    },
    '07/05/2018':{
        'a':53,
        'b':13,
        'c':2
    },
    '07/06/2018':{
        'a':21,
        'b':15,
        'c':7
    }
}
}
export default categoryByTime