
const townOptions = [
        {
            key:'新營區',
            value:'新營區',
            text:'新營區',
            minor : [
                {
                  key:'民生里',
                  text:'民生里',
                  value:'民生里',
                }, 
                {
                  key:'嘉芳里',
                  text:'嘉芳里',
                  value:'嘉芳里',
                },
                {
                  key:'新南里',
                  text:'新南里',
                  value:'新南里',
                }, 
                {
                  key:'姑爺里',
                  text:'姑爺里',
                  value:'姑爺里',
                },
                {
                  key:'興業里',
                  text:'興業里',
                  value:'興業里',
                }, 
                {
                  key:'五興里',
                  text:'五興里',
                  value:'五興里',
                },
                {
                  key:'太南里',
                  text:'太南里',
                  value:'太南里',
                }, 
                {
                  key:'中營里',
                  text:'中營里',
                  value:'中營里',
                },
                {
                  key:'三仙里',
                  text:'三仙里',
                  value:'三仙里',
                }, 
                {
                  key:'忠政里',
                  text:'忠政里',
                  value:'忠政里',
                },
                {
                  key:'王公里',
                  text:'王公里',
                  value:'王公里',
                },
                {
                  key:'新東里',
                  text:'新東里',
                  value:'新東里',
                }, 
                {
                  key:'民權里',
                  text:'民權里',
                  value:'民權里',
                },
                {
                  key:'永平里',
                  text:'永平里',
                  value:'永平里',
                }, 
                {
                  key:'民榮里',
                  text:'民榮里',
                  value:'民榮里',
                },
                {
                  key:'南紙里',
                  text:'南紙里',
                  value:'南紙里',
                }, 
                {
                  key:'土庫里',
                  text:'土庫里',
                  value:'土庫里',
                },
                {
                  key:'埤寮里',
                  text:'埤寮里',
                  value:'埤寮里',
                }, 
                {
                  key:'南興里',
                  text:'南興里',
                  value:'南興里',
                },
                {
                  key:'太北里',
                  text:'太北里',
                  value:'太北里',
                }, 
                {
                  key:'大宏里',
                  text:'大宏里',
                  value:'大宏里',
                },
                {
                  key:'新北里',
                  text:'新北里',
                  value:'新北里',
                }, 
                {
                  key:'護鎮里',
                  text:'護鎮里',
                  value:'護鎮里',
                },
               
              ], 
        },{
            key:'鹽水區',
            value:'鹽水區',
            text:'鹽水區',
            minor : [
                {
                  key:'歡雅里',
                  text:'歡雅里',
                  value:'歡雅里',
                }, 
                {
                  key:'橋南里',
                  text:'橋南里',
                  value:'橋南里',
                },
                {
                  key:'水秀里',
                  text:'水秀里',
                  value:'水秀里',
                }, 
                {
                  key:'岸內里',
                  text:'岸內里',
                  value:'岸內里',
                },
                {
                  key:'汫水里',
                  text:'汫水里',
                  value:'汫水里',
                }, 
                {
                  key:'津城里',
                  text:'津城里',
                  value:'津城里',
                },
                {
                  key:'月港里',
                  text:'月港里',
                  value:'月港里',
                }, 
                {
                  key:'三明里',
                  text:'三明里',
                  value:'三明里',
                },
                {
                  key:'義中里',
                  text:'義中里',
                  value:'義中里',
                }, 
                {
                  key:'文昌里',
                  text:'文昌里',
                  value:'文昌里',
                },
                {
                  key:'竹林里',
                  text:'竹林里',
                  value:'竹林里',
                }, 
                {
                  key:'三和里',
                  text:'三和里',
                  value:'三和里',
                },
                {
                  key:'頭港里',
                  text:'頭港里',
                  value:'頭港里',
                },
              ], 
        },
        {
            key:'白河區',
            value:'白河區',
            text:'白河區',
            minor : [
                {
                  key:'六溪里',
                  text:'六溪里',
                  value:'六溪里',
                }, 
                {
                  key:'崁頭里',
                  text:'崁頭里',
                  value:'崁頭里',
                },
                {
                  key:'大林里',
                  text:'大林里',
                  value:'大林里',
                }, 
                {
                  key:'關嶺里',
                  text:'關嶺里',
                  value:'關嶺里',
                },
                {
                  key:'外角里',
                  text:'外角里',
                  value:'外角里',
                }, 
                {
                  key:'白河里',
                  text:'白河里',
                  value:'白河里',
                },
                {
                  key:'河東里',
                  text:'河東里',
                  value:'河東里',
                }, 
                {
                  key:'永安里',
                  text:'永安里',
                  value:'永安里',
                },
                {
                  key:'秀祐里',
                  text:'秀祐里',
                  value:'秀祐里',
                }, 
                {
                  key:'庄內里',
                  text:'庄內里',
                  value:'庄內里',
                },
                {
                  key:'虎山里',
                  text:'虎山里',
                  value:'虎山里',
                }, 
                {
                  key:'仙草里',
                  text:'仙草里',
                  value:'仙草里',
                },
                {
                  key:'大竹里',
                  text:'大竹里',
                  value:'大竹里',
                }, 
                {
                  key:'汴頭里',
                  text:'汴頭里',
                  value:'汴頭里',
                },
                {
                  key:'昇安里',
                  text:'昇安里',
                  value:'昇安里',
                }, 
                {
                  key:'竹門里',
                  text:'竹門里',
                  value:'竹門里',
                },
                {
                  key:'內角里',
                  text:'內角里',
                  value:'內角里',
                }, 
                {
                  key:'廣蓮里',
                  text:'廣蓮里',
                  value:'廣蓮里',
                },
                {
                  key:'詔豐里',
                  text:'詔豐里',
                  value:'詔豐里',
                }, 
                {
                  key:'馬稠後里',
                  text:'馬稠後里',
                  value:'馬稠後里',
                },
                {
                  key:'崎內里',
                  text:'崎內里',
                  value:'崎內里',
                },
              ], 
        },
        {
            key:'柳營區',
            value:'柳營區',
            text:'柳營區',
            minor : [
                {
                  key:'中埕里',
                  text:'中埕里',
                  value:'中埕里',
                }, 
                {
                  key:'光福里',
                  text:'光福里',
                  value:'光福里',
                },
                {
                  key:'神農里',
                  text:'神農里',
                  value:'神農里',
                }, 
                {
                  key:'果毅里',
                  text:'果毅里',
                  value:'果毅里',
                },
                {
                  key:'八翁里',
                  text:'八翁里',
                  value:'八翁里',
                }, 
                {
                  key:'士林里',
                  text:'士林里',
                  value:'士林里',
                },
                {
                  key:'東昇里',
                  text:'東昇里',
                  value:'東昇里',
                }, 
                {
                  key:'大農里',
                  text:'大農里',
                  value:'大農里',
                },
                {
                  key:'人和里',
                  text:'人和里',
                  value:'人和里',
                }, 
                {
                  key:'篤農里',
                  text:'篤農里',
                  value:'篤農里',
                },
                {
                  key:'重溪里',
                  text:'重溪里',
                  value:'重溪里',
                }, 
                {
                  key:'太康里',
                  text:'太康里',
                  value:'太康里',
                },
                {
                  key:'旭山里',
                  text:'旭山里',
                  value:'旭山里',
                },
              ], 
        },
        {
            key:'後壁區',
            value:'後壁區',
            text:'後壁區',
            minor : [
                {
                  key:'頂安里',
                  text:'頂安里',
                  value:'頂安里',
                }, 
                {
                  key:'新東里',
                  text:'新東里',
                  value:'新東里',
                },
                {
                  key:'竹新里',
                  text:'竹新里',
                  value:'竹新里',
                }, 
                {
                  key:'嘉苳里',
                  text:'嘉苳里',
                  value:'嘉苳里',
                },
                {
                  key:'後壁里',
                  text:'後壁里',
                  value:'後壁里',
                }, 
                {
                  key:'侯伯里',
                  text:'侯伯里',
                  value:'侯伯里',
                },
                {
                  key:'新嘉里',
                  text:'新嘉里',
                  value:'新嘉里',
                }, 
                {
                  key:'土溝里',
                  text:'土溝里',
                  value:'土溝里',
                },
                {
                  key:'福安里',
                  text:'福安里',
                  value:'福安里',
                }, 
                {
                  key:'長安里',
                  text:'長安里',
                  value:'長安里',
                },
                {
                  key:'菁寮里',
                  text:'菁寮里',
                  value:'菁寮里',
                }, 
                {
                  key:'上茄苳里',
                  text:'上茄苳里',
                  value:'上茄苳里',
                },
                {
                  key:'菁豐里',
                  text:'菁豐里',
                  value:'菁豐里',
                }, 
                {
                  key:'長短樹里',
                  text:'長短樹里',
                  value:'長短樹里',
                },
              ], 
        },
        {
            key:'東山區',
            value:'東山區',
            text:'東山區',
            minor : [
                {
                  key:'嶺南里',
                  text:'嶺南里',
                  value:'嶺南里',
                }, 
                {
                  key:'南勢里',
                  text:'南勢里',
                  value:'南勢里',
                },
                {
                  key:'青山里',
                  text:'青山里',
                  value:'青山里',
                }, 
                {
                  key:'水雲里',
                  text:'水雲里',
                  value:'水雲里',
                },
                {
                  key:'林安里',
                  text:'林安里',
                  value:'林安里',
                }, 
                {
                  key:'東河里',
                  text:'東河里',
                  value:'東河里',
                },
                {
                  key:'東中里',
                  text:'東中里',
                  value:'東中里',
                }, 
                {
                  key:'聖賢里',
                  text:'聖賢里',
                  value:'聖賢里',
                },
                {
                  key:'東正里',
                  text:'東正里',
                  value:'東正里',
                }, 
                {
                  key:'三榮里',
                  text:'三榮里',
                  value:'三榮里',
                },
                {
                  key:'東山里',
                  text:'東山里',
                  value:'東山里',
                }, 
                {
                  key:'南溪里',
                  text:'南溪里',
                  value:'南溪里',
                },
                {
                  key:'高原里',
                  text:'高原里',
                  value:'高原里',
                }, 
                {
                  key:'科里里',
                  text:'科里里',
                  value:'科里里',
                },
                {
                  key:'東原里',
                  text:'東原里',
                  value:'東原里',
                }, 
                {
                  key:'大客里',
                  text:'大客里',
                  value:'大客里',
                },
              ], 
        },
        {
            key: '麻豆區',
            value: '麻豆區',
            text: '麻豆區',
            minor : [
                {
                  key:'埤頭里',
                  text:'埤頭里',
                  value:'埤頭里',
                }, 
                {
                  key:'海埔里',
                  text:'海埔里',
                  value:'海埔里',
                },
                {
                  key:'安正里',
                  text:'安正里',
                  value:'安正里',
                }, 
                {
                  key:'興農里',
                  text:'興農里',
                  value:'興農里',
                },
                {
                  key:'中興里',
                  text:'中興里',
                  value:'中興里',
                }, 
                {
                  key:'晉江里',
                  text:'晉江里',
                  value:'晉江里',
                },
                {
                  key:'東角里',
                  text:'東角里',
                  value:'東角里',
                }, 
                {
                  key:'麻口里',
                  text:'麻口里',
                  value:'麻口里',
                },
                {
                  key:'油車里',
                  text:'油車里',
                  value:'油車里',
                }, 
                {
                  key:'大埕里',
                  text:'大埕里',
                  value:'大埕里',
                },
                {
                  key:'寮部里',
                  text:'寮部里',
                  value:'寮部里',
                }, 
                {
                  key:'新興里',
                  text:'新興里',
                  value:'新興里',
                },
                {
                  key:'謝厝寮里',
                  text:'謝厝寮里',
                  value:'謝厝寮里',
                }, 
                {
                  key:'井東里',
                  text:'井東里',
                  value:'井東里',
                },
                {
                  key:'清水里',
                  text:'清水里',
                  value:'清水里',
                }, 
                {
                  key:'北勢里',
                  text:'北勢里',
                  value:'北勢里',
                },
                {
                  key:'安業里',
                  text:'安業里',
                  value:'安業里',
                }, 
                {
                  key:'巷口里',
                  text:'巷口里',
                  value:'巷口里',
                },
                {
                  key:'南勢里',
                  text:'南勢里',
                  value:'南勢里',
                }, 
                {
                  key:'港尾里',
                  text:'港尾里',
                  value:'港尾里',
                },
              ], 
        },
        {
            key:'下營區',
            value: '下營區',
            text: '下營區',
            minor : [
                {
                  key:'開化里',
                  text:'開化里',
                  value:'開化里',
                }, 
                {
                  key:'西連里',
                  text:'西連里',
                  value:'西連里',
                },
                {
                  key:'營前里',
                  text:'營前里',
                  value:'營前里',
                }, 
                {
                  key:'賀建里',
                  text:'賀建里',
                  value:'賀建里',
                },
                {
                  key:'下營里',
                  text:'下營里',
                  value:'下營里',
                }, 
                {
                  key:'宅內里',
                  text:'宅內里',
                  value:'宅內里',
                },
                {
                  key:'後街里',
                  text:'後街里',
                  value:'後街里',
                }, 
                {
                  key:'仁里里',
                  text:'仁里里',
                  value:'仁里里',
                },
                {
                  key:'新興里',
                  text:'新興里',
                  value:'新興里',
                }, 
                {
                  key:'大吉里',
                  text:'大吉里',
                  value:'大吉里',
                },
                {
                  key:'茅營里',
                  text:'茅營里',
                  value:'茅營里',
                }, 
                {
                  key:'紅甲里',
                  text:'紅甲里',
                  value:'紅甲里',
                },
              ], 
        },
        {
            key:'六甲區',
            value:'六甲區',
            text:'六甲區',
            minor : [
                {
                  key:'七甲里',
                  text:'七甲里',
                  value:'七甲里',
                }, 
                {
                  key:'甲南里',
                  text:'甲南里',
                  value:'甲南里',
                },
                {
                  key:'二甲里',
                  text:'二甲里',
                  value:'二甲里',
                }, 
                {
                  key:'六甲里',
                  text:'六甲里',
                  value:'六甲里',
                },
                {
                  key:'王爺里',
                  text:'王爺里',
                  value:'王爺里',
                }, 
                {
                  key:'甲東里',
                  text:'甲東里',
                  value:'甲東里',
                },
                {
                  key:'大丘里',
                  text:'大丘里',
                  value:'大丘里',
                }, 
                {
                  key:'菁埔里',
                  text:'菁埔里',
                  value:'菁埔里',
                },
                {
                  key:'龜港里',
                  text:'龜港里',
                  value:'龜港里',
                }, 
                {
                  key:'中社里',
                  text:'中社里',
                  value:'中社里',
                },
                {
                  key:'水林里',
                  text:'水林里',
                  value:'水林里',
                },
              ], 
        },
        {
            key: '官田區',
            value: '官田區',
            text: '官田區',
            minor : [
                {
                  key:'社子里',
                  text:'社子里',
                  value:'社子里',
                }, 
                {
                  key:'隆田里',
                  text:'隆田里',
                  value:'隆田里',
                },
                {
                  key:'官田里',
                  text:'官田里',
                  value:'官田里',
                }, 
                {
                  key:'隆本里',
                  text:'隆本里',
                  value:'隆本里',
                },
                {
                  key:'大崎里',
                  text:'大崎里',
                  value:'大崎里',
                }, 
                {
                  key:'二鎮里',
                  text:'二鎮里',
                  value:'二鎮里',
                },
                {
                  key:'南部里',
                  text:'南部里',
                  value:'南部里',
                }, 
                {
                  key:'渡拔里',
                  text:'渡拔里',
                  value:'渡拔里',
                },
                {
                  key:'烏山頭里',
                  text:'烏山頭里',
                  value:'烏山頭里',
                },
                {
                  key:'東西庄里',
                  text:'東西庄里',
                  value:'東西庄里',
                }, 
              ], 
        },
        {
            key: '大內區',
            value: '大內區',
            text: '大內區',
            minor : [
                {
                  key:'內江里',
                  text:'內江里',
                  value:'內江里',
                }, 
                {
                  key:'石城里',
                  text:'石城里',
                  value:'石城里',
                },
                {
                  key:'大內里',
                  text:'大內里',
                  value:'大內里',
                }, 
                {
                  key:'曲溪里',
                  text:'曲溪里',
                  value:'曲溪里',
                },
                {
                  key:'內郭里',
                  text:'內郭里',
                  value:'內郭里',
                }, 
                {
                  key:'石林里',
                  text:'石林里',
                  value:'石林里',
                },
                {
                  key:'二溪里',
                  text:'二溪里',
                  value:'二溪里',
                }, 
                {
                  key:'石湖里',
                  text:'石湖里',
                  value:'石湖里',
                },
                {
                  key:'頭社里',
                  text:'頭社里',
                  value:'頭社里',
                }, 
                {
                  key:'環湖里',
                  text:'環湖里',
                  value:'環湖里',
                },
              ], 
        },
        {
            key: '佳里區',
            value: '佳里區',
            text: '佳里區',
            minor : [
                {
                  key:'鎮山里',
                  text:'鎮山里',
                  value:'鎮山里',
                }, 
                {
                  key:'忠仁里',
                  text:'忠仁里',
                  value:'忠仁里',
                },
                {
                  key:'民安里',
                  text:'民安里',
                  value:'民安里',
                }, 
                {
                  key:'佳化里',
                  text:'佳化里',
                  value:'佳化里',
                },
                {
                  key:'東寧里',
                  text:'東寧里',
                  value:'東寧里',
                }, 
                {
                  key:'安西里',
                  text:'安西里',
                  value:'安西里',
                },
                {
                  key:'六安里',
                  text:'六安里',
                  value:'六安里',
                }, 
                {
                  key:'建南里',
                  text:'建南里',
                  value:'建南里',
                },
                {
                  key:'下營里',
                  text:'下營里',
                  value:'下營里',
                }, 
                {
                  key:'營溪里',
                  text:'營溪里',
                  value:'營溪里',
                },
                {
                  key:'塭內里',
                  text:'塭內里',
                  value:'塭內里',
                }, 
                {
                  key:'佳興里',
                  text:'佳興里',
                  value:'佳興里',
                },
                {
                  key:'南勢里',
                  text:'南勢里',
                  value:'南勢里',
                }, 
                {
                  key:'文新里',
                  text:'文新里',
                  value:'文新里',
                },
                {
                  key:'子龍里',
                  text:'子龍里',
                  value:'子龍里',
                }, 
                {
                  key:'海澄里',
                  text:'海澄里',
                  value:'海澄里',
                },
              ], 
        },
        {
            key: '學甲區',
            value: '學甲區',
            text: '學甲區',
            minor : [
                {
                  key:'大灣里',
                  text:'大灣里',
                  value:'大灣里',
                }, 
                {
                  key:'豐和里',
                  text:'豐和里',
                  value:'豐和里',
                },
                {
                  key:'新榮里',
                  text:'新榮里',
                  value:'新榮里',
                }, 
                {
                  key:'慈福里',
                  text:'慈福里',
                  value:'慈福里',
                },
                {
                  key:'仁得里',
                  text:'仁得里',
                  value:'仁得里',
                }, 
                {
                  key:'新達里',
                  text:'新達里',
                  value:'新達里',
                },
                {
                  key:'中洲里',
                  text:'中洲里',
                  value:'中洲里',
                }, 
                {
                  key:'平和里',
                  text:'平和里',
                  value:'平和里',
                },
                {
                  key:'宅港里',
                  text:'宅港里',
                  value:'宅港里',
                }, 
                {
                  key:'三慶里',
                  text:'三慶里',
                  value:'三慶里',
                },
                {
                  key:'明宜里',
                  text:'明宜里',
                  value:'明宜里',
                }, 
                {
                  key:'秀昌里',
                  text:'秀昌里',
                  value:'秀昌里',
                },
                {
                  key:'光華里',
                  text:'光華里',
                  value:'光華里',
                }, 
            
              ], 
        },
        {
            key: '西港區',
            value:'西港區',
            text: '西港區',
            minor : [
                {
                  key:'港東里',
                  text:'港東里',
                  value:'港東里',
                }, 
                {
                  key:'金砂里',
                  text:'金砂里',
                  value:'金砂里',
                },
                {
                  key:'檨林里',
                  text:'檨林里',
                  value:'檨林里',
                }, 
                {
                  key:'營西里',
                  text:'營西里',
                  value:'營西里',
                },
                {
                  key:'後營里',
                  text:'後營里',
                  value:'後營里',
                }, 
                {
                  key:'永樂里',
                  text:'永樂里',
                  value:'永樂里',
                },
                {
                  key:'新復里',
                  text:'新復里',
                  value:'新復里',
                }, 
                {
                  key:'南海里',
                  text:'南海里',
                  value:'南海里',
                },
                {
                  key:'竹林里',
                  text:'竹林里',
                  value:'竹林里',
                }, 
                {
                  key:'劉厝里',
                  text:'劉厝里',
                  value:'劉厝里',
                },
                {
                  key:'西港里',
                  text:'西港里',
                  value:'西港里',
                }, 
                {
                  key:'慶安里',
                  text:'慶安里',
                  value:'慶安里',
                },
              ], 
        },
        {
            key:  '新化區',
            value: '新化區',
            text:  '新化區',
            minor : [
                {
                  key:'知義里',
                  text:'知義里',
                  value:'知義里',
                }, 
                {
                  key:'武安里',
                  text:'武安里',
                  value:'武安里',
                },
                {
                  key:'豐榮里',
                  text:'豐榮里',
                  value:'豐榮里',
                }, 
                {
                  key:'護國里',
                  text:'護國里',
                  value:'護國里',
                },
                {
                  key:'那拔里',
                  text:'那拔里',
                  value:'那拔里',
                }, 
                {
                  key:'大坑里',
                  text:'大坑里',
                  value:'大坑里',
                },
                {
                  key:'東榮里',
                  text:'東榮里',
                  value:'東榮里',
                }, 
                {
                  key:'礁坑里',
                  text:'礁坑里',
                  value:'礁坑里',
                },
                {
                  key:'羊林里',
                  text:'羊林里',
                  value:'羊林里',
                }, 
                {
                  key:'山腳里',
                  text:'山腳里',
                  value:'山腳里',
                },
                {
                  key:'崙頂里',
                  text:'崙頂里',
                  value:'崙頂里',
                }, 
                {
                  key:'全興里',
                  text:'全興里',
                  value:'全興里',
                },
                {
                  key:'太平里',
                  text:'太平里',
                  value:'太平里',
                }, 
                {
                  key:'協興里',
                  text:'協興里',
                  value:'協興里',
                },
                {
                  key:'唪口里',
                  text:'唪口里',
                  value:'唪口里',
                }, 
                {
                  key:'北勢里',
                  text:'北勢里',
                  value:'北勢里',
                },
              ], 
        },
        {
            key: '善化區',
            value:'善化區',
            text: '善化區',
            minor : [
                {
                  key:'文正里',
                  text:'文正里',
                  value:'文正里',
                }, 
                {
                  key:'什乃里',
                  text:'什乃里',
                  value:'什乃里',
                },
                {
                  key:'溪美里',
                  text:'溪美里',
                  value:'溪美里',
                }, 
                {
                  key:'六分里',
                  text:'六分里',
                  value:'六分里',
                },
                {
                  key:'六德里',
                  text:'六德里',
                  value:'六德里',
                }, 
                {
                  key:'嘉南里',
                  text:'嘉南里',
                  value:'嘉南里',
                },
                {
                  key:'蓮潭里',
                  text:'蓮潭里',
                  value:'蓮潭里',
                }, 
                {
                  key:'昌隆里',
                  text:'昌隆里',
                  value:'昌隆里',
                },
                {
                  key:'頂街里',
                  text:'頂街里',
                  value:'頂街里',
                }, 
                {
                  key:'文昌里',
                  text:'文昌里',
                  value:'文昌里',
                },
                {
                  key:'坐駕里',
                  text:'坐駕里',
                  value:'坐駕里',
                }, 
                {
                  key:'南關里',
                  text:'南關里',
                  value:'南關里',
                },
                {
                  key:'小新里',
                  text:'小新里',
                  value:'小新里',
                }, 
                {
                  key:'東關里',
                  text:'東關里',
                  value:'東關里',
                },
                {
                  key:'牛庄里',
                  text:'牛庄里',
                  value:'牛庄里',
                }, 
                {
                  key:'光文里',
                  text:'光文里',
                  value:'光文里',
                },
                {
                  key:'胡厝里',
                  text:'胡厝里',
                  value:'胡厝里',
                }, 
                {
                  key:'田寮里',
                  text:'田寮里',
                  value:'田寮里',
                },
                {
                  key:'嘉北里',
                  text:'嘉北里',
                  value:'嘉北里',
                }, 
                {
                  key:'胡家里',
                  text:'胡家里',
                  value:'胡家里',
                },
              ], 
        },
        {
            key:  '新市區',
            value: '新市區',
            text:  '新市區',
            minor : [
                {
                  key:'永就里',
                  text:'永就里',
                  value:'永就里',
                }, 
                {
                  key:'大洲里',
                  text:'大洲里',
                  value:'大洲里',
                },
                {
                  key:'新和里',
                  text:'新和里',
                  value:'新和里',
                }, 
                {
                  key:'新市里',
                  text:'新市里',
                  value:'新市里',
                },
                {
                  key:'港墘里',
                  text:'港墘里',
                  value:'港墘里',
                }, 
                {
                  key:'社內里',
                  text:'社內里',
                  value:'社內里',
                },
                {
                  key:'豐華里',
                  text:'豐華里',
                  value:'豐華里',
                }, 
                {
                  key:'三舍里',
                  text:'三舍里',
                  value:'三舍里',
                },
                {
                  key:'大社里',
                  text:'大社里',
                  value:'大社里',
                }, 
                {
                  key:'潭頂里',
                  text:'潭頂里',
                  value:'潭頂里',
                },
                {
                  key:'大營里',
                  text:'大營里',
                  value:'大營里',
                },
              ], 
        },
        {
            key:'安定區',
            value:'安定區',
            text:'安定區',
            minor : [
                {
                  key:'中沙里',
                  text:'中沙里',
                  value:'中沙里',
                }, 
                {
                  key:'新吉里',
                  text:'新吉里',
                  value:'新吉里',
                },
                {
                  key:'港南里',
                  text:'港南里',
                  value:'港南里',
                }, 
                {
                  key:'港口里',
                  text:'港口里',
                  value:'港口里',
                },
                {
                  key:'中榮里',
                  text:'中榮里',
                  value:'中榮里',
                }, 
                {
                  key:'海寮里',
                  text:'海寮里',
                  value:'海寮里',
                },
                {
                  key:'港尾里',
                  text:'港尾里',
                  value:'港尾里',
                }, 
                {
                  key:'安定里',
                  text:'安定里',
                  value:'安定里',
                },
                {
                  key:'蘇厝里',
                  text:'蘇厝里',
                  value:'蘇厝里',
                }, 
                {
                  key:'蘇林里',
                  text:'蘇林里',
                  value:'蘇林里',
                },
                {
                  key:'嘉同里',
                  text:'嘉同里',
                  value:'嘉同里',
                }, 
                {
                  key:'文科里',
                  text:'文科里',
                  value:'文科里',
                },
                {
                  key:'安加里',
                  text:'安加里',
                  value:'安加里',
                }, 
               
              ], 
        },    
        {
            key:'山上區',
            value:'山上區',
            text:'山上區',
            minor : [
                {
                  key:'豐德里',
                  text:'豐德里',
                  value:'豐德里',
                }, 
                {
                  key:'平陽里',
                  text:'平陽里',
                  value:'平陽里',
                },
                {
                  key:'南洲里',
                  text:'南洲里',
                  value:'南洲里',
                }, 
                {
                  key:'玉峰里',
                  text:'玉峰里',
                  value:'玉峰里',
                },
                {
                  key:'新莊里',
                  text:'新莊里',
                  value:'新莊里',
                },
                {
                  key:'山上里',
                  text:'山上里',
                  value:'山上里',
                }, 
                {
                  key:'明和里',
                  text:'明和里',
                  value:'明和里',
                },
              ], 
        },
        {
            key:'玉井區',
            value:'玉井區',
            text:'玉井區',
            minor : [
                {
                  key:'玉田里',
                  text:'玉田里',
                  value:'玉田里',
                }, 
                {
                  key:'玉井里',
                  text:'玉井里',
                  value:'玉井里',
                },
                {
                  key:'層林里',
                  text:'層林里',
                  value:'層林里',
                }, 
                {
                  key:'三埔里',
                  text:'三埔里',
                  value:'三埔里',
                },
                {
                  key:'望明里',
                  text:'望明里',
                  value:'望明里',
                }, 
                {
                  key:'三和里',
                  text:'三和里',
                  value:'三和里',
                },
                {
                  key:'沙田里',
                  text:'沙田里',
                  value:'沙田里',
                }, 
                {
                  key:'竹圍里',
                  text:'竹圍里',
                  value:'竹圍里',
                },
                {
                  key:'中正里',
                  text:'中正里',
                  value:'中正里',
                }, 
                {
                  key:'豐里里',
                  text:'豐里里',
                  value:'豐里里',
                },
              ], 
        },
        {
            key: '楠西區',
            value: '楠西區',
            text: '楠西區',
            minor : [
                {
                  key:'龜丹里',
                  text:'龜丹里',
                  value:'龜丹里',
                }, 
                {
                  key:'鹿田里',
                  text:'鹿田里',
                  value:'鹿田里',
                },
                {
                  key:'東勢里',
                  text:'東勢里',
                  value:'東勢里',
                }, 
                {
                  key:'楠西里',
                  text:'楠西里',
                  value:'楠西里',
                },
                {
                  key:'灣丘里',
                  text:'灣丘里',
                  value:'灣丘里',
                }, 
                {
                  key:'照興里',
                  text:'照興里',
                  value:'照興里',
                },
                {
                  key:'密枝里',
                  text:'密枝里',
                  value:'密枝里',
                },
              ], 
        },
        {
            key:  '南化區',
            value:  '南化區',
            text:  '南化區',
            minor : [
                {
                  key:'東和里',
                  text:'東和里',
                  value:'東和里',
                }, 
                {
                  key:'南化里',
                  text:'南化里',
                  value:'南化里',
                },
                {
                  key:'西埔里',
                  text:'西埔里',
                  value:'西埔里',
                }, 
                {
                  key:'中坑里',
                  text:'中坑里',
                  value:'中坑里',
                },
                {
                  key:'小崙里',
                  text:'小崙里',
                  value:'小崙里',
                }, 
                {
                  key:'北平里',
                  text:'北平里',
                  value:'北平里',
                },
                {
                  key:'北寮里',
                  text:'北寮里',
                  value:'北寮里',
                }, 
                {
                  key:'玉山里',
                  text:'玉山里',
                  value:'玉山里',
                },
                {
                  key:'關山里',
                  text:'關山里',
                  value:'關山里',
                }, 
              
              ], 
        },
        {
            key: '左鎮區',
            value:  '左鎮區',
            text:  '左鎮區',
            minor : [
                {
                  key:'二寮里',
                  text:'二寮里',
                  value:'二寮里',
                }, 
                {
                  key:'草山里',
                  text:'草山里',
                  value:'草山里',
                },
                {
                  key:'岡林里',
                  text:'岡林里',
                  value:'岡林里',
                }, 
                {
                  key:'內庄里',
                  text:'內庄里',
                  value:'內庄里',
                },
                {
                  key:'澄山里',
                  text:'澄山里',
                  value:'澄山里',
                }, 
                {
                  key:'左鎮里',
                  text:'左鎮里',
                  value:'左鎮里',
                },
                {
                  key:'睦光里',
                  text:'睦光里',
                  value:'睦光里',
                }, 
                {
                  key:'中正里',
                  text:'中正里',
                  value:'中正里',
                },
                {
                  key:'光和里',
                  text:'光和里',
                  value:'光和里',
                }, 
                {
                  key:'榮和里',
                  text:'榮和里',
                  value:'榮和里',
                },
               
              ], 
        },
        {
            key:'仁德區',
            value:'仁德區',
            text:'仁德區',
            minor : [
                {
                  key:'保安里',
                  text:'保安里',
                  value:'保安里',
                }, 
                {
                  key:'上崙里',
                  text:'上崙里',
                  value:'上崙里',
                },
                {
                  key:'後壁里',
                  text:'後壁里',
                  value:'後壁里',
                }, 
                {
                  key:'成功里',
                  text:'成功里',
                  value:'成功里',
                },
                {
                  key:'仁和里',
                  text:'仁和里',
                  value:'仁和里',
                }, 
                {
                  key:'仁愛里',
                  text:'仁愛里',
                  value:'仁愛里',
                },
                {
                  key:'仁德里',
                  text:'仁德里',
                  value:'仁德里',
                }, 
                {
                  key:'新田里',
                  text:'新田里',
                  value:'新田里',
                },
                {
                  key:'一甲里',
                  text:'一甲里',
                  value:'一甲里',
                }, 
                {
                  key:'中洲里',
                  text:'中洲里',
                  value:'中洲里',
                },
                {
                  key:'文賢里',
                  text:'文賢里',
                  value:'文賢里',
                }, 
                {
                  key:'二行里',
                  text:'二行里',
                  value:'二行里',
                },
                {
                  key:'大甲里',
                  text:'大甲里',
                  value:'大甲里',
                }, 
                {
                  key:'仁義里',
                  text:'仁義里',
                  value:'仁義里',
                },
                {
                  key:'土庫里',
                  text:'土庫里',
                  value:'土庫里',
                }, 
                {
                  key:'太子里',
                  text:'太子里',
                  value:'太子里',
                },
              ], 
        },            
        {
            key:  '歸仁區',
            value:  '歸仁區',
            text:  '歸仁區',
            minor : [
                {
                  key:'六甲里',
                  text:'六甲里',
                  value:'六甲里',
                }, 
                {
                  key:'大潭里',
                  text:'大潭里',
                  value:'大潭里',
                },
                {
                  key:'許厝里',
                  text:'許厝里',
                  value:'許厝里',
                }, 
                {
                  key:'歸仁里',
                  text:'歸仁里',
                  value:'歸仁里',
                },
                {
                  key:'文化里',
                  text:'文化里',
                  value:'文化里',
                }, 
                {
                  key:'八甲里',
                  text:'八甲里',
                  value:'八甲里',
                },
                {
                  key:'媽廟里',
                  text:'媽廟里',
                  value:'媽廟里',
                }, 
                {
                  key:'新厝里',
                  text:'新厝里',
                  value:'新厝里',
                },
                {
                  key:'七甲里',
                  text:'七甲里',
                  value:'七甲里',
                }, 
                {
                  key:'崙頂里',
                  text:'崙頂里',
                  value:'崙頂里',
                },
                {
                  key:'辜厝里',
                  text:'辜厝里',
                  value:'辜厝里',
                }, 
                {
                  key:'後市里',
                  text:'後市里',
                  value:'後市里',
                },
                {
                  key:'看西里',
                  text:'看西里',
                  value:'看西里',
                }, 
                {
                  key:'看東里',
                  text:'看東里',
                  value:'看東里',
                },
                {
                  key:'大廟里',
                  text:'大廟里',
                  value:'大廟里',
                }, 
                {
                  key:'西埔里',
                  text:'西埔里',
                  value:'西埔里',
                },
                {
                  key:'歸南里',
                  text:'歸南里',
                  value:'歸南里',
                }, 
                {
                  key:'南保里',
                  text:'南保里',
                  value:'南保里',
                },
                {
                  key:'武東里',
                  text:'武東里',
                  value:'武東里',
                }, 
                {
                  key:'沙崙里',
                  text:'沙崙里',
                  value:'沙崙里',
                },
                {
                  key:'南興里',
                  text:'南興里',
                  value:'南興里',
                },
                
              ], 
        },
        {
            key:  '關廟區',
            value:  '關廟區',
            text:  '關廟區',
            minor : [
                {
                  key:'布袋里',
                  text:'布袋里',
                  value:'布袋里',
                }, 
                {
                  key:'深坑里',
                  text:'深坑里',
                  value:'深坑里',
                },
                {
                  key:'下湖里',
                  text:'下湖里',
                  value:'下湖里',
                }, 
                {
                  key:'埤頭里',
                  text:'埤頭里',
                  value:'埤頭里',
                },
                {
                  key:'五甲里',
                  text:'五甲里',
                  value:'五甲里',
                }, 
                {
                  key:'東勢里',
                  text:'東勢里',
                  value:'東勢里',
                },
                {
                  key:'松腳里',
                  text:'松腳里',
                  value:'松腳里',
                }, 
                {
                  key:'關廟里',
                  text:'關廟里',
                  value:'關廟里',
                },
                {
                  key:'香洋里',
                  text:'香洋里',
                  value:'香洋里',
                }, 
                {
                  key:'北勢里',
                  text:'北勢里',
                  value:'北勢里',
                },
                {
                  key:'新光里',
                  text:'新光里',
                  value:'新光里',
                }, 
                {
                  key:'南雄里',
                  text:'南雄里',
                  value:'南雄里',
                },
                {
                  key:'花園里',
                  text:'花園里',
                  value:'花園里',
                },
                {
                  key:'山西里',
                  text:'山西里',
                  value:'山西里',
                }, 
                {
                  key:'新埔里',
                  text:'新埔里',
                  value:'新埔里',
                },
              ], 
        },
        {
            key: '龍崎區',
            value: '龍崎區',
            text: '龍崎區',
            minor : [
                {
                  key:'牛埔里',
                  text:'牛埔里',
                  value:'牛埔里',
                }, 
                {
                  key:'楠坑里',
                  text:'楠坑里',
                  value:'楠坑里',
                },
                {
                  key:'大坪里',
                  text:'大坪里',
                  value:'大坪里',
                }, 
                {
                  key:'龍船里',
                  text:'龍船里',
                  value:'龍船里',
                },
                {
                  key:'中坑里',
                  text:'中坑里',
                  value:'中坑里',
                }, 
                {
                  key:'石曹里',
                  text:'石曹里',
                  value:'石曹里',
                },
                {
                  key:'崎頂里',
                  text:'崎頂里',
                  value:'崎頂里',
                }, 
                {
                  key:'土崎里',
                  text:'土崎里',
                  value:'土崎里',
                },
              ], 
        },
        {
            key: '永康區',
            value:'永康區',
            text: '永康區',
            minor : [
                {
                  key:'東灣里',
                  text:'東灣里',
                  value:'東灣里',
                }, 
                {
                  key:'南灣里',
                  text:'南灣里',
                  value:'南灣里',
                },
                {
                  key:'崑山里',
                  text:'崑山里',
                  value:'崑山里',
                }, 
                {
                  key:'大灣里',
                  text:'大灣里',
                  value:'大灣里',
                },
                {
                  key:'五王里',
                  text:'五王里',
                  value:'五王里',
                }, 
                {
                  key:'西灣里',
                  text:'西灣里',
                  value:'西灣里',
                },
                {
                  key:'安康里',
                  text:'安康里',
                  value:'安康里',
                }, 
                {
                  key:'西橋里',
                  text:'西橋里',
                  value:'西橋里',
                },
                {
                  key:'網寮里',
                  text:'網寮里',
                  value:'網寮里',
                }, 
                {
                  key:'大橋里',
                  text:'大橋里',
                  value:'大橋里',
                },
                {
                  key:'甲頂里',
                  text:'甲頂里',
                  value:'甲頂里',
                }, 
                {
                  key:'永康里',
                  text:'永康里',
                  value:'永康里',
                },
                {
                  key:'東橋里',
                  text:'東橋里',
                  value:'東橋里',
                }, 
                {
                  key:'正強里',
                  text:'正強里',
                  value:'正強里',
                },
                {
                  key:'烏竹里',
                  text:'烏竹里',
                  value:'烏竹里',
                }, 
                {
                  key:'王行里',
                  text:'王行里',
                  value:'王行里',
                },
                {
                  key:'新樹里',
                  text:'新樹里',
                  value:'新樹里',
                }, 
                {
                  key:'鹽行里',
                  text:'鹽行里',
                  value:'鹽行里',
                },
                {
                  key:'龍埔里',
                  text:'龍埔里',
                  value:'龍埔里',
                }, 
                {
                  key:'永明里',
                  text:'永明里',
                  value:'永明里',
                },
                {
                  key:'鹽洲里',
                  text:'鹽洲里',
                  value:'鹽洲里',
                }, 
                {
                  key:'鹽興里',
                  text:'鹽興里',
                  value:'鹽興里',
                },
                {
                  key:'北灣里',
                  text:'北灣里',
                  value:'北灣里',
                }, 
                {
                  key:'北興里',
                  text:'北興里',
                  value:'北興里',
                },
                {
                  key:'尚頂里',
                  text:'尚頂里',
                  value:'尚頂里',
                }, 
                {
                  key:'龍潭里',
                  text:'龍潭里',
                  value:'龍潭里',
                },
                {
                  key:'埔園里',
                  text:'埔園里',
                  value:'埔園里',
                }, 
                {
                  key:'三民里',
                  text:'三民里',
                  value:'三民里',
                },
                {
                  key:'光復里',
                  text:'光復里',
                  value:'光復里',
                }, 
                {
                  key:'勝利里',
                  text:'勝利里',
                  value:'勝利里',
                },
                {
                  key:'建國里',
                  text:'建國里',
                  value:'建國里',
                },
                {
                  key:'六合里',
                  text:'六合里',
                  value:'六合里',
                }, 
                {
                  key:'中華里',
                  text:'中華里',
                  value:'中華里',
                },
                {
                  key:'成功里',
                  text:'成功里',
                  value:'成功里',
                }, 
                {
                  key:'復興里',
                  text:'復興里',
                  value:'復興里',
                },
                {
                  key:'神洲里',
                  text:'神洲里',
                  value:'神洲里',
                }, 
                {
                  key:'中興里',
                  text:'中興里',
                  value:'中興里',
                },
                {
                  key:'復國里',
                  text:'復國里',
                  value:'復國里',
                }, 
                {
                  key:'三合里',
                  text:'三合里',
                  value:'三合里',
                },
                {
                  key:'復華里',
                  text:'復華里',
                  value:'復華里',
                }, 
                {
                  key:'二王里',
                  text:'二王里',
                  value:'二王里',
                },
                {
                  key:'西勢里',
                  text:'西勢里',
                  value:'西勢里',
                }, 
                {
                  key:'蔦松里',
                  text:'蔦松里',
                  value:'蔦松里',
                },
              ], 
        },
        {
            key:   '北區',
            value:  '北區',
            text:   '北區',
            minor : [
                {
                  key:'公園里',
                  text:'公園里',
                  value:'公園里',
                }, 
                {
                  key:'中樓里',
                  text:'中樓里',
                  value:'中樓里',
                },
                {
                  key:'公園里',
                  text:'公園里',
                  value:'公園里',
                }, 
                {
                  key:'賢北里',
                  text:'賢北里',
                  value:'賢北里',
                },
                {
                  key:'大豐里',
                  text:'大豐里',
                  value:'大豐里',
                }, 
                {
                  key:'大港里',
                  text:'大港里',
                  value:'大港里',
                },
                {
                  key:'正覺里',
                  text:'正覺里',
                  value:'正覺里',
                }, 
                {
                  key:'大和里',
                  text:'大和里',
                  value:'大和里',
                },
                {
                  key:'成功里',
                  text:'成功里',
                  value:'成功里',
                }, 
                {
                  key:'北華里',
                  text:'北華里',
                  value:'北華里',
                },
                {
                  key:'華德里',
                  text:'華德里',
                  value:'華德里',
                }, 
                {
                  key:'福德里',
                  text:'福德里',
                  value:'福德里',
                },
                {
                  key:'長勝里',
                  text:'長勝里',
                  value:'長勝里',
                }, 
                {
                  key:'長興里',
                  text:'長興里',
                  value:'長興里',
                },
                {
                  key:'大興里',
                  text:'大興里',
                  value:'大興里',
                }, 
                {
                  key:'大光里',
                  text:'大光里',
                  value:'大光里',
                },
                {
                  key:'小北里',
                  text:'小北里',
                  value:'小北里',
                }, 
                {
                  key:'雙安里',
                  text:'雙安里',
                  value:'雙安里',
                },
                {
                  key:'立人里',
                  text:'立人里',
                  value:'立人里',
                }, 
                {
                  key:'北門里',
                  text:'北門里',
                  value:'北門里',
                },
                {
                  key:'東興里',
                  text:'東興里',
                  value:'東興里',
                }, 
                {
                  key:'重興里',
                  text:'重興里',
                  value:'重興里',
                },
                {
                  key:'和順里',
                  text:'和順里',
                  value:'和順里',
                }, 
                {
                  key:'力行里',
                  text:'力行里',
                  value:'力行里',
                },
                {
                  key:'文成里',
                  text:'文成里',
                  value:'文成里',
                }, 
                {
                  key:'元寶里',
                  text:'元寶里',
                  value:'元寶里',
                },
                {
                  key:'開元里',
                  text:'開元里',
                  value:'開元里',
                }, 
                {
                  key:'成德里',
                  text:'成德里',
                  value:'成德里',
                },
                {
                  key:'元美里',
                  text:'元美里',
                  value:'元美里',
                }, 
                {
                  key:'合興里',
                  text:'合興里',
                  value:'合興里',
                },
                {
                  key:'仁愛里',
                  text:'仁愛里',
                  value:'仁愛里',
                }, 
                {
                  key:'振興里',
                  text:'振興里',
                  value:'振興里',
                },
                {
                  key:'永祥里',
                  text:'永祥里',
                  value:'永祥里',
                }, 
                {
                  key:'文元里',
                  text:'文元里',
                  value:'文元里',
                },
               
              ], 
        },
        {
            key:  '七股區',
            value: '七股區',
            text:  '七股區',
            minor : [
                {
                  key:'溪南里',
                  text:'溪南里',
                  value:'溪南里',
                }, 
                {
                  key:'七股里',
                  text:'七股里',
                  value:'七股里',
                },
                {
                  key:'龍山里',
                  text:'龍山里',
                  value:'龍山里',
                }, 
                {
                  key:'中寮里',
                  text:'中寮里',
                  value:'中寮里',
                },
                {
                  key:'篤加里',
                  text:'篤加里',
                  value:'篤加里',
                }, 
                {
                  key:'鹽埕里',
                  text:'鹽埕里',
                  value:'鹽埕里',
                },
                {
                  key:'三股里',
                  text:'三股里',
                  value:'三股里',
                }, 
                {
                  key:'十份里',
                  text:'十份里',
                  value:'十份里',
                },
                {
                  key:'永吉里',
                  text:'永吉里',
                  value:'永吉里',
                }, 
                {
                  key:'頂山里',
                  text:'頂山里',
                  value:'頂山里',
                },
                {
                  key:'大潭里',
                  text:'大潭里',
                  value:'大潭里',
                }, 
                {
                  key:'義合里',
                  text:'義合里',
                  value:'義合里',
                },
                {
                  key:'竹橋里',
                  text:'竹橋里',
                  value:'竹橋里',
                }, 
                {
                  key:'大埕里',
                  text:'大埕里',
                  value:'大埕里',
                },
                {
                  key:'後港里',
                  text:'後港里',
                  value:'後港里',
                }, 
                {
                  key:'玉成里',
                  text:'玉成里',
                  value:'玉成里',
                },
                {
                  key:'西寮里',
                  text:'西寮里',
                  value:'西寮里',
                }, 
                {
                  key:'樹林里',
                  text:'樹林里',
                  value:'樹林里',
                },
              ], 
        },
        {
            key:   '將軍區',
            value:  '將軍區',
            text:   '將軍區',
            minor : [
                {
                  key:'長榮里',
                  text:'長榮里',
                  value:'長榮里',
                }, 
                {
                  key:'玉山里',
                  text:'玉山里',
                  value:'玉山里',
                },
                {
                  key:'廣山里',
                  text:'廣山里',
                  value:'廣山里',
                }, 
                {
                  key:'平沙里',
                  text:'平沙里',
                  value:'平沙里',
                },
                {
                  key:'長沙里',
                  text:'長沙里',
                  value:'長沙里',
                }, 
                {
                  key:'鯤鯓里',
                  text:'鯤鯓里',
                  value:'鯤鯓里',
                },
                {
                  key:'忠嘉里',
                  text:'忠嘉里',
                  value:'忠嘉里',
                }, 
                {
                  key:'西甲里',
                  text:'西甲里',
                  value:'西甲里',
                },
                {
                  key:'苓仔寮里',
                  text:'苓仔寮里',
                  value:'苓仔寮里',
                }, 
                {
                  key:'巷埔里',
                  text:'巷埔里',
                  value:'巷埔里',
                },
                {
                  key:'將軍里',
                  text:'將軍里',
                  value:'將軍里',
                }, 
                {
                  key:'鯤溟里',
                  text:'鯤溟里',
                  value:'鯤溟里',
                },
              ], 
        },
        {
            key:   '北門區',
            value:  '北門區',
            text:   '北門區',
            minor : [
                {
                  key:'三光里',
                  text:'三光里',
                  value:'三光里',
                }, 
                {
                  key:'玉港里',
                  text:'玉港里',
                  value:'玉港里',
                },
                {
                  key:'三光里',
                  text:'三光里',
                  value:'三光里',
                }, 
                {
                  key:'保吉里',
                  text:'保吉里',
                  value:'保吉里',
                },
                {
                  key:'錦湖里',
                  text:'錦湖里',
                  value:'錦湖里',
                }, 
                {
                  key:'慈安里',
                  text:'慈安里',
                  value:'慈安里',
                },
                {
                  key:'雙春里',
                  text:'雙春里',
                  value:'雙春里',
                }, 
                {
                  key:'北門里',
                  text:'北門里',
                  value:'北門里',
                },
                {
                  key:'永隆里',
                  text:'永隆里',
                  value:'永隆里',
                }, 
                {
                  key:'蚵寮里',
                  text:'蚵寮里',
                  value:'蚵寮里',
                },
                {
                  key:'文山里',
                  text:'文山里',
                  value:'文山里',
                },
              ], 
        },
        {
            key:   '安南區',
            value:  '安南區',
            text:   '安南區',
            minor : [
                {
                  key:'青草里',
                  text:'青草里',
                  value:'青草里',
                }, 
                {
                  key:'城北里',
                  text:'城北里',
                  value:'城北里',
                },
                {
                  key:'城南里',
                  text:'城南里',
                  value:'城南里',
                }, 
                {
                  key:'海南里',
                  text:'海南里',
                  value:'海南里',
                },
                {
                  key:'國安里',
                  text:'國安里',
                  value:'國安里',
                }, 
                {
                  key:'溪心里',
                  text:'溪心里',
                  value:'溪心里',
                },
                {
                  key:'淵東里',
                  text:'淵東里',
                  value:'淵東里',
                }, 
                {
                  key:'城中里',
                  text:'城中里',
                  value:'城中里',
                },
                {
                  key:'城東里',
                  text:'城東里',
                  value:'城東里',
                }, 
                {
                  key:'學東里',
                  text:'學東里',
                  value:'學東里',
                },
                {
                  key:'溪頂里',
                  text:'溪頂里',
                  value:'溪頂里',
                }, 
                {
                  key:'海佃里',
                  text:'海佃里',
                  value:'海佃里',
                },
                {
                  key:'溪東里',
                  text:'溪東里',
                  value:'溪東里',
                }, 
                {
                  key:'溪北里',
                  text:'溪北里',
                  value:'溪北里',
                },
                {
                  key:'溪墘里',
                  text:'溪墘里',
                  value:'溪墘里',
                }, 
                {
                  key:'安富里',
                  text:'安富里',
                  value:'安富里',
                },
                {
                  key:'鹽田里',
                  text:'鹽田里',
                  value:'鹽田里',
                }, 
                {
                  key:'鳳凰里',
                  text:'鳳凰里',
                  value:'鳳凰里',
                },
                {
                  key:'公親里',
                  text:'公親里',
                  value:'公親里',
                }, 
                {
                  key:'砂崙里',
                  text:'砂崙里',
                  value:'砂崙里',
                },
                {
                  key:'幸福里',
                  text:'幸福里',
                  value:'幸福里',
                }, 
                {
                  key:'四草里',
                  text:'四草里',
                  value:'四草里',
                },
                {
                  key:'安東里',
                  text:'安東里',
                  value:'安東里',
                }, 
                {
                  key:'淵中里',
                  text:'淵中里',
                  value:'淵中里',
                },
                {
                  key:'城西里',
                  text:'城西里',
                  value:'城西里',
                }, 
                {
                  key:'佃東里',
                  text:'佃東里',
                  value:'佃東里',
                },
                {
                  key:'新順里',
                  text:'新順里',
                  value:'新順里',
                }, 
                {
                  key:'鹿耳里',
                  text:'鹿耳里',
                  value:'鹿耳里',
                },
                {
                  key:'海西里',
                  text:'海西里',
                  value:'海西里',
                }, 
                {
                  key:'佃西里',
                  text:'佃西里',
                  value:'佃西里',
                },
                {
                  key:'安西里',
                  text:'安西里',
                  value:'安西里',
                }, 
                {
                  key:'大安里',
                  text:'大安里',
                  value:'大安里',
                },
                {
                  key:'安和里',
                  text:'安和里',
                  value:'安和里',
                }, 
                {
                  key:'理想里',
                  text:'理想里',
                  value:'理想里',
                },
                {
                  key:'安慶里',
                  text:'安慶里',
                  value:'安慶里',
                }, 
                {
                  key:'梅花里',
                  text:'梅花里',
                  value:'梅花里',
                },
                {
                  key:'頂安里',
                  text:'頂安里',
                  value:'頂安里',
                }, 
                {
                  key:'安順里',
                  text:'安順里',
                  value:'安順里',
                },
                {
                  key:'總頭里',
                  text:'總頭里',
                  value:'總頭里',
                }, 
                {
                  key:'原佃里',
                  text:'原佃里',
                  value:'原佃里',
                },
                {
                  key:'東和里',
                  text:'東和里',
                  value:'東和里',
                }, 
                {
                  key:'淵西里',
                  text:'淵西里',
                  value:'淵西里',
                },
                {
                  key:'長安里',
                  text:'長安里',
                  value:'長安里',
                }, 
                {
                  key:'顯宮里',
                  text:'顯宮里',
                  value:'顯宮里',
                },
                {
                  key:'州南里',
                  text:'州南里',
                  value:'州南里',
                }, 
                {
                  key:'布袋里',
                  text:'布袋里',
                  value:'布袋里',
                },
                {
                  key:'州北里',
                  text:'州北里',
                  value:'州北里',
                }, 
                {
                  key:'塭南里',
                  text:'塭南里',
                  value:'塭南里',
                },
                {
                  key:'公塭里',
                  text:'公塭里',
                  value:'公塭里',
                }, 
                {
                  key:'南興里',
                  text:'南興里',
                  value:'南興里',
                },
                {
                  key:'海東里',
                  text:'海東里',
                  value:'海東里',
                },
              ], 
        },
        {
            key:    '南區',
            value:   '南區',
            text:    '南區',
            minor : [
                {
                  key:'大成里',
                  text:'大成里',
                  value:'大成里',
                }, 
                {
                  key:'佛壇里',
                  text:'佛壇里',
                  value:'佛壇里',
                },
                {
                  key:'同安里',
                  text:'同安里',
                  value:'同安里',
                }, 
                {
                  key:'松安里',
                  text:'松安里',
                  value:'松安里',
                },
                {
                  key:'永寧里',
                  text:'永寧里',
                  value:'永寧里',
                }, 
                {
                  key:'喜南里',
                  text:'喜南里',
                  value:'喜南里',
                },
                {
                  key:'喜東里',
                  text:'喜東里',
                  value:'喜東里',
                }, 
                {
                  key:'喜北里',
                  text:'喜北里',
                  value:'喜北里',
                },
                {
                  key:'南都里',
                  text:'南都里',
                  value:'南都里',
                }, 
                {
                  key:'南華里',
                  text:'南華里',
                  value:'南華里',
                },
                {
                  key:'建南里',
                  text:'建南里',
                  value:'建南里',
                }, 
                {
                  key:'明興里',
                  text:'明興里',
                  value:'明興里',
                },
                {
                  key:'郡南里',
                  text:'郡南里',
                  value:'郡南里',
                }, 
                {
                  key:'開南里',
                  text:'開南里',
                  value:'開南里',
                },
                {
                  key:'明亮里',
                  text:'明亮里',
                  value:'明亮里',
                }, 
                {
                  key:'鯤鯓里',
                  text:'鯤鯓里',
                  value:'鯤鯓里',
                },
                {
                  key:'大忠里',
                  text:'大忠里',
                  value:'大忠里',
                }, 
                {
                  key:'光明里',
                  text:'光明里',
                  value:'光明里',
                },
                {
                  key:'府南里',
                  text:'府南里',
                  value:'府南里',
                }, 
                {
                  key:'大林里',
                  text:'大林里',
                  value:'大林里',
                },
                {
                  key:'國宅里',
                  text:'國宅里',
                  value:'國宅里',
                }, 
                {
                  key:'田寮里',
                  text:'田寮里',
                  value:'田寮里',
                },
                {
                  key:'新生里',
                  text:'新生里',
                  value:'新生里',
                }, 
                {
                  key:'竹溪里',
                  text:'竹溪里',
                  value:'竹溪里',
                },
                {
                  key:'明德里',
                  text:'明德里',
                  value:'明德里',
                }, 
                {
                  key:'再興里',
                  text:'再興里',
                  value:'再興里',
                },
                {
                  key:'彰南里',
                  text:'彰南里',
                  value:'彰南里',
                }, 
                {
                  key:'金華里',
                  text:'金華里',
                  value:'金華里',
                },
                {
                  key:'新興里',
                  text:'新興里',
                  value:'新興里',
                }, 
                {
                  key:'文南里',
                  text:'文南里',
                  value:'文南里',
                },
                {
                  key:'新昌里',
                  text:'新昌里',
                  value:'新昌里',
                },
                {
                  key:'廣州里',
                  text:'廣州里',
                  value:'廣州里',
                }, 
                {
                  key:'文華里',
                  text:'文華里',
                  value:'文華里',
                },
                {
                  key:'興農里',
                  text:'興農里',
                  value:'興農里',
                },
                {
                  key:'省躬里',
                  text:'省躬里',
                  value:'省躬里',
                },
                {
                  key:'大恩里',
                  text:'大恩里',
                  value:'大恩里',
                }, 
                {
                  key:'鹽埕里',
                  text:'鹽埕里',
                  value:'鹽埕里',
                },
              ], 
        },
        {
            key:   '東區',
            value: '東區',
            text:   '東區',
            minor : [
                {
                  key:'大智里',
                  text:'大智里',
                  value:'大智里',
                }, 
                {
                  key:'崇文里',
                  text:'崇文里',
                  value:'崇文里',
                },
                {
                  key:'崇成里',
                  text:'崇成里',
                  value:'崇成里',
                }, 
                {
                  key:'崇明里',
                  text:'崇明里',
                  value:'崇明里',
                },
                {
                  key:'大福里',
                  text:'大福里',
                  value:'大福里',
                }, 
                {
                  key:'崇德里',
                  text:'崇德里',
                  value:'崇德里',
                },
                {
                  key:'大德里',
                  text:'大德里',
                  value:'大德里',
                }, 
                {
                  key:'崇學里',
                  text:'崇學里',
                  value:'崇學里',
                },
                {
                  key:'和平里',
                  text:'和平里',
                  value:'和平里',
                }, 
                {
                  key:'崇善里',
                  text:'崇善里',
                  value:'崇善里',
                },
                {
                  key:'路東里',
                  text:'路東里',
                  value:'路東里',
                }, 
                {
                  key:'虎尾里',
                  text:'虎尾里',
                  value:'虎尾里',
                },
                {
                  key:'忠孝里',
                  text:'忠孝里',
                  value:'忠孝里',
                }, 
                {
                  key:'裕聖里',
                  text:'裕聖里',
                  value:'裕聖里',
                },
                {
                  key:'崇信里',
                  text:'崇信里',
                  value:'崇信里',
                }, 
                {
                  key:'德光里',
                  text:'德光里',
                  value:'德光里',
                },
                {
                  key:'復興里',
                  text:'復興里',
                  value:'復興里',
                }, 
                {
                  key:'自強里',
                  text:'自強里',
                  value:'自強里',
                },
                {
                  key:'文聖里',
                  text:'文聖里',
                  value:'文聖里',
                }, 
                {
                  key:'富裕里',
                  text:'富裕里',
                  value:'富裕里',
                },
                {
                  key:'龍山里',
                  text:'龍山里',
                  value:'龍山里',
                }, 
                {
                  key:'關聖里',
                  text:'關聖里',
                  value:'關聖里',
                },
                {
                  key:'新東里',
                  text:'新東里',
                  value:'新東里',
                }, 
                {
                  key:'富強里',
                  text:'富強里',
                  value:'富強里',
                },
                {
                  key:'泉南里',
                  text:'泉南里',
                  value:'泉南里',
                }, 
                {
                  key:'東聖里',
                  text:'東聖里',
                  value:'東聖里',
                },
                {
                  key:'東安里',
                  text:'東安里',
                  value:'東安里',
                }, 
                {
                  key:'大同里',
                  text:'大同里',
                  value:'大同里',
                },
                {
                  key:'衛國里',
                  text:'衛國里',
                  value:'衛國里',
                }, 
                {
                  key:'裕農里',
                  text:'裕農里',
                  value:'裕農里',
                },
                {
                  key:'南聖里',
                  text:'南聖里',
                  value:'南聖里',
                }, 
                {
                  key:'崇誨里',
                  text:'崇誨里',
                  value:'崇誨里',
                },
                {
                  key:'東門里',
                  text:'東門里',
                  value:'東門里',
                }, 
                {
                  key:'中西里',
                  text:'中西里',
                  value:'中西里',
                },
                {
                  key:'東明里',
                  text:'東明里',
                  value:'東明里',
                }, 
                {
                  key:'圍下里',
                  text:'圍下里',
                  value:'圍下里',
                },
                {
                  key:'東光里',
                  text:'東光里',
                  value:'東光里',
                },
                {
                  key:'後甲里',
                  text:'後甲里',
                  value:'後甲里',
                }, 
                {
                  key:'莊敬里',
                  text:'莊敬里',
                  value:'莊敬里',
                },
                {
                  key:'小東里',
                  text:'小東里',
                  value:'小東里',
                },
                {
                  key:'大學里',
                  text:'大學里',
                  value:'大學里',
                }, 
                {
                  key:'成大里',
                  text:'成大里',
                  value:'成大里',
                },
                {
                  key:'德高里',
                  text:'德高里',
                  value:'德高里',
                },
                {
                  key:'仁和里',
                  text:'仁和里',
                  value:'仁和里',
                }, 
                {
                  key:'東智里',
                  text:'東智里',
                  value:'東智里',
                },
              ], 
        },
        {
            key:    '安平區',
            value:   '安平區',
            text:    '安平區',
            minor : [
                {
                  key:'文平里',
                  text:'文平里',
                  value:'文平里',
                }, 
                {
                  key:'國平里',
                  text:'國平里',
                  value:'國平里',
                },
                {
                  key:'育平里',
                  text:'育平里',
                  value:'育平里',
                }, 
                {
                  key:'漁光里',
                  text:'漁光里',
                  value:'漁光里',
                },
                {
                  key:'華平里',
                  text:'華平里',
                  value:'華平里',
                }, 
                {
                  key:'怡平里',
                  text:'怡平里',
                  value:'怡平里',
                },
                {
                  key:'建平里',
                  text:'建平里',
                  value:'建平里',
                }, 
                {
                  key:'金城里',
                  text:'金城里',
                  value:'金城里',
                },
                {
                  key:'平安里',
                  text:'平安里',
                  value:'平安里',
                }, 
                {
                  key:'王城里',
                  text:'王城里',
                  value:'王城里',
                },
                {
                  key:'天妃里',
                  text:'天妃里',
                  value:'天妃里',
                },
                {
                  key:'億載里',
                  text:'億載里',
                  value:'億載里',
                }, 
                {
                  key:'平通里',
                  text:'平通里',
                  value:'平通里',
                },
              ], 
        },
        {
            key:   '中西區',
            value: '中西區',
            text:   '中西區',
            minor : [
                {
                  key:'赤嵌里',
                  text:'赤嵌里',
                  value:'赤嵌里',
                }, 
                {
                  key:'法華里',
                  text:'法華里',
                  value:'法華里',
                },
                {
                  key:'西湖里',
                  text:'西湖里',
                  value:'西湖里',
                }, 
                {
                  key:'西賢里',
                  text:'西賢里',
                  value:'西賢里',
                },
                {
                  key:'小西門里',
                  text:'小西門里',
                  value:'小西門里',
                }, 
                {
                  key:'兌悅里',
                  text:'兌悅里',
                  value:'兌悅里',
                },
                {
                  key:'五條港里',
                  text:'五條港里',
                  value:'五條港里',
                }, 
                {
                  key:'南美里',
                  text:'南美里',
                  value:'南美里',
                },
                {
                  key:'城隍里',
                  text:'城隍里',
                  value:'城隍里',
                }, 
                {
                  key:'西和里',
                  text:'西和里',
                  value:'西和里',
                },
                {
                  key:'永華里',
                  text:'永華里',
                  value:'永華里',
                }, 
                {
                  key:'郡王里',
                  text:'郡王里',
                  value:'郡王里',
                },
                {
                  key:'南廠里',
                  text:'南廠里',
                  value:'南廠里',
                }, 
                {
                  key:'淺草里',
                  text:'淺草里',
                  value:'淺草里',
                },
                {
                  key:'府前里',
                  text:'府前里',
                  value:'府前里',
                }, 
                {
                  key:'南門里',
                  text:'南門里',
                  value:'南門里',
                },
                {
                  key:'開山里',
                  text:'開山里',
                  value:'開山里',
                }, 
                {
                  key:'大涼里',
                  text:'大涼里',
                  value:'大涼里',
                },
                {
                  key:'藥王里',
                  text:'藥王里',
                  value:'藥王里',
                }, 
                {
                  key:'光賢里',
                  text:'光賢里',
                  value:'光賢里',
                },
              ], 
        },  
    ]        
export default townOptions                         
               